### ISSUE TITLE
Foreman opens for some others when another player uses some foreman buttons

### ISSUE THREAD

**Issue by Nexela** [Choumiko/Foreman#16]
Minor issue. Noticed this in Arumba MASA videos

Have not looked too deep into but my thoughts are guiSettings.windowVisable  is not getting set to false in some cases when closing the gui or removing the button via hotykeys

**Comment by Choumiko** [comment]
Not as painfully to fix as i thought, let's hope this actually fixes it. Not in the mood to setup a multiplayer just now ;)
