### ISSUE TITLE
Blueprints broken in 0.12.33

### ISSUE THREAD

**Issue by emichael** [Choumiko/Foreman#4]
The blueprints appear correct in the preview window and in the green ghost state when the blueprint is selected, but when I try to place them, things get weird. Certain items get shifted, and certain ones don't get placed at all, depending on the orientation.

Looking at the change log, it looks like this was fixed, but I don't see any option to fix my blueprints, and they don't get auto-converted.

**Comment by credomane** [comment]
Sadly this is actually a Factorio Bug/issue. The devs made some changes to blueprints in 12.31, 12.32 and 12.33. The end results is most/all existing blueprints have to be rebuilt unfortunately.

There are two options neither of which are great. First is the slow manual process of remaking them by hand according to the held-in-hand look of the blueprint. This will require knowing the state of buildings too.

The other way is to export all of your blueprints with foreman then with the newest foreman reimport each one individually and use the "Fix Positions" checkbox on the import dialog. This fixed 99% of my blueprints. There were a few I still had to manually remake.

[edit]  
Also don't use the "fix positions" to import blueprints made with 12.13 or newer or it will offset buildings. Resulting in what would have been a good blueprint being broken.

BTW, is it possible for you to paste the blueprint string here? post s link to a github gist or something for easy copy-n-paste.

**Comment by Choumiko** [comment]
Foreman blueprints (the ones you have "saved" in the gui and the ones you paste from a file should get autofixed if necessary. If you use an actual blueprint string (from the Blueprintstring mod) it get's a little tricky since a Blueprintstring doesn't contain any info whether it was fixed or not. 
If your blueprints come from Blueprintstring, try importing them without the "fix positions" checkbox first, if they are messed up try it with.

**Comment by emichael** [comment]
They didn't get autofixed, that's the issue.

**Comment by Choumiko** [comment]
Since i can't reproduce it i added a console command: https://github.com/Choumiko/Foreman/releases/tag/v0.1.23
