### ISSUE TITLE
Factorio 0.13 No longer require green circuit to clear blueprints.

### ISSUE THREAD

**Issue by credomane** [Choumiko/Foreman#9]
Foreman still requires green circuits to clear a blueprint but Factorio no longer requires this.

**Comment by Choumiko** [comment]
Interesting, i didn't know that. Thanks for the report.
Fixing now, proper release will come later/tomorrow, with a few other changes

**Comment by credomane** [comment]
I didn't either. I was messing around and got that warning from foreman. Thought nothing of it for a second then realized I had been clearing blueprints for a while without circuits.

Intentionally tested it and sure enough. Factorio 0.13 no longer needs green circuits to clear blueprints. Just watch now that you've done this 0.13.7 comes out tomorrow and fixes that and you'll need to revert your commit. lol
